DROP TABLE IF EXISTS POST_ID;
CREATE TABLE POST_ID(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    POST_ID VARCHAR(10) UNIQUE,
    IS_DOWNLOAD ENUM('0','1','2') -- 0:未下载过 1:下载成功 2:下载失败
);


DROP TABLE IF EXISTS POST_CONTENT;
CREATE TABLE POST_CONTENT(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    POST_ID VARCHAR(10) NOT NULL UNIQUE,
    TITLE VARCHAR(100) NOT NULL,
    DATE VARCHAR(100) NOT NULL,
    LOCATION VARCHAR(100) NOT NULL,
    ENV VARCHAR(100) NOT NULL,
    PRICE VARCHAR(100) NOT NULL,
    KEYPOINT VARCHAR(100) NOT NULL,
    DETAIL VARCHAR(3000) NOT NULL
);
